name: Create workload zone

on:
  workflow_dispatch:
    inputs:
      workload_environment:
        description: 'Workload zone configuration name, example: DEV, PROD'
        required: true
        type: string
        default: 'DEV'
      workload_region:
        description: 'Workload zone region, example: eastus, westus'
        required: true
        type: string
        default: 'eastus'
      workload_vnet:
        description: 'Workload zone VNET, example: SAP01, SAP02'
        required: true
        type: string
        default: 'SAP01'
      deployer_environment:
        description: 'The control plane environment to use.'
        required: true
        default: 'dev'

permissions:
  issues: write
  contents: write
  actions: write

jobs:
  create_workload_zone:
    name: Create workload zone
    runs-on: ubuntu-latest
    environment: "${{ inputs.deployer_environment }}"
    container:
      image: ghcr.io/devanshjainms/sap-automation:devanshjain-githubworkflow
    steps:
      - name: Get app token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
          #organization: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}

      - name: Create GitHub Environment for workload zone
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          workload_environment=${{ inputs.workload_environment }}
          region=${{ inputs.workload_region }}
          deployer_name=${{ inputs.deployer_environment }}
          workload_vnet=${{ inputs.workload_vnet }}

          pushd /source/deploy/terraform/terraform-units/modules/sap_namegenerator
          region_map=$(echo var.region_mapping.${region} | terraform console | tr -d '"')
          popd

          echo region_map: $region_map
          echo region: $region

          workload_environment_config=${workload_environment}-${region_map}-${workload_vnet}-INFRASTRUCTURE

          url_to_call=/repos/${{ github.repository }}/environments/${workload_environment_config^^}

          _=$(gh api \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            ${url_to_call})

          mkdir -p WORKSPACES/LANDSCAPE/${workload_environment_config^^}

          cat .cfg_template/workloadzone.tfvars \
            | sed "s|@@ENV@@|${environment}|g" \
            | sed "s|@@REGION@@|${region}|g" \
            | sed "s|@@VNET@@|${workload_vnet}|g" \
            | sed "s|@@REGION_DISPLAY_NAME@@|${region}|g" \
            > WORKSPACES/LANDSCAPE/${workload_environment_config^^}/${workload_environment_config^^}.tfvars

          # Update the environment in the issue-closed workflow
          workspace=$(ls ${GITHUB_WORKSPACE}/WORKSPACES|tail -n 1)

          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git config --global user.name "GitHub Actions"
          git config --global user.email "sap-automation-deployer@noreply.github.com"

          git add WORKSPACES/LANDSCAPE/${workload_environment_config^^}

          git commit -m "Add folder for ${workload_environment} in ${region}"
          git push

